# Generated by Django 2.2.10 on 2020-08-05 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Poll Name')),
                ('text', models.TextField(verbose_name='Poll description')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Date created')),
                ('date_changed', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date changed')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Date Start')),
            ],
            options={
                'verbose_name': 'Poll',
                'verbose_name_plural': 'Polls',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Text')),
                ('question_type', models.CharField(choices=[('TEXT', 'Answer with text'), ('SINGLE', 'Single vote'), ('MANY', 'Many votes')], max_length=10, verbose_name='Question Type')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.Poll', verbose_name='Poll')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Question Vote Text')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionvotes', to='polls.Question', verbose_name='Question')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.PositiveIntegerField(blank=True, null=True, verbose_name='USER ID')),
                ('vote', models.BooleanField(default=False, verbose_name='Vote')),
                ('answer_text', models.TextField(blank=True, null=True, verbose_name='Question Text Answer')),
                ('questionvote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.QuestionVote', verbose_name='QuestionVote')),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
            },
        ),
    ]
