# Generated by Django 2.2.10 on 2020-08-05 22:35

from django.db import migrations
from django.apps import apps
from django.core.management.sql import emit_post_migrate_signal


def make_permissions(apps, schema_editor, with_create_permissions=True):
    emit_post_migrate_signal(2, False, 'default')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    perms = (
        'view_poll',
        'add_poll',
        'change_poll',
        'delete_poll'
    )

    group = Group.objects.create(
        name='polls admin'
    )
    for i in perms:
        try:
            perm = Permission.objects.get(
                codename=i, content_type__app_label='polls')
        except Permission.DoesNotExist:
            if with_create_permissions:
                from django.contrib.auth.management import create_permissions
                assert not getattr(apps, 'models_module', None)
                apps.models_module = True
                create_permissions(apps, verbosity=0)
                apps.models_module = None
                return make_permissions(
                    apps, schema_editor, with_create_permissions=False)
            else:
                raise
        group.permissions.add(perm)


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(make_permissions)
    ]
